jobs:
  mirror:
    runs-on: ubuntu-latest

    env:
      BRANCH: dev_by_tg

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "Mirror Bot"
          git config --global user.email "mirror@bot.com"

      - name: Clone GitLab repo
        run: |
          GITLAB_REPO="https://${{ secrets.GLAB_USERNAME }}:${{ secrets.GLAB_PAT }}@gitlab.com/WhiteOrangeSoftware/homehive_flutter.git"
          git clone --single-branch --branch "$BRANCH" "$GITLAB_REPO" repo
          cd repo
          git remote add github "https://${{ secrets.GH_TOKEN }}@github.com/qcabrol/homehive_flutter.git"

      - name: Force push to GitHub
        run: |
          cd repo
          git push github "$BRANCH:$BRANCH" --force
